[package]
name = "lemons-search"
version = "0.1.0"
authors = ["Moritz Jung <m.projects.code@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
# we stay on this version since 0.2.93 has some error when passing large arrays
wasm-bindgen = "=0.2.92"
console_error_panic_hook = { version = "0.1.7", optional = true }
nucleo-matcher = "0.3.1"
itertools = "0.13.0"
speedy = "=0.8.7"
web-sys = { version = "0.3.69", features = ["Worker"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.42"

[profile.release]
opt-level = 3               # Highest level of optimization.
lto = "fat"                 # Enable link-time optimization.
overflow-checks = false     # Disable integer overflow checks.
incremental = true          # Enable incremental compilation for faster builds.
